train: ../train/images
val: ../valid/images
test: ../test/images

nc: 1
names: ['0']

roboflow:
  workspace: yolov8-pz2dc
  project: yolo_retrain_tol_butac
  version: 3
  license: CC BY 4.0
  url: https://universe.roboflow.com/yolov8-pz2dc/yolo_retrain_tol_butac/dataset/3